#!/bin/sh
rm -rf *.bak
rm -rf *.orig
rm -rf *.rej
rm -rf *~
rm -rf db
rm -rf incremental_db
rm -rf output_files
rm -rf simulation
rm -rf greybox_tmp
rm -rf hc_output
rm -rf .qsys_edit
rm -rf hps_isw_handoff
rm -rf sys/.qsys_edit
rm -rf sys/vip
rm -rf sys/*_sim
rm -rf rtl/*_sim
rm -rf build_id.v
rm -rf c5_pin_morm_dump.txt
rm -rf PLLJ_PLLSPE_INFO.txt
rm -rf *.qws
rm -rf *.ppf
rm -rf *.ddb
rm -rf *.csv
rm -rf *.cmp
rm -rf *.sip
rm -rf *.spd
rm -rf *.bsf
rm -rf *.f
rm -rf *.sopcinfo
rm -rf *.xml
rm -rf *.cdf
rm -rf *.rpt
rm -rf new_rtl_netlist
rm -rf old_rtl_netlist