# TCL File Generated by Component Editor 17.0
# Mon Feb 25 20:51:40 GMT 2019
# DO NOT MODIFY


# 
# joystick "joystick" v1.0
#  2019.02.25.20:51:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module joystick
# 
set_module_property DESCRIPTION ""
set_module_property NAME joystick
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME joystick
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL joystick
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file joystick.v VERILOG PATH rtl/soc/sound/joystick.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset Input 1


# 
# connection point joy
# 
add_interface joy avalon end
set_interface_property joy addressUnits WORDS
set_interface_property joy associatedClock clock
set_interface_property joy associatedReset reset
set_interface_property joy bitsPerSymbol 8
set_interface_property joy burstOnBurstBoundariesOnly false
set_interface_property joy burstcountUnits WORDS
set_interface_property joy explicitAddressSpan 0
set_interface_property joy holdTime 0
set_interface_property joy linewrapBursts false
set_interface_property joy maximumPendingReadTransactions 0
set_interface_property joy maximumPendingWriteTransactions 0
set_interface_property joy readLatency 0
set_interface_property joy readWaitStates 0
set_interface_property joy readWaitTime 0
set_interface_property joy setupTime 0
set_interface_property joy timingUnits Cycles
set_interface_property joy writeWaitTime 0
set_interface_property joy ENABLED true
set_interface_property joy EXPORT_OF ""
set_interface_property joy PORT_NAME_MAP ""
set_interface_property joy CMSIS_SVD_VARIABLES ""
set_interface_property joy SVD_ADDRESS_GROUP ""

add_interface_port joy joy_address address Input 3
add_interface_port joy joy_read read Input 1
add_interface_port joy joy_readdata readdata Output 8
add_interface_port joy joy_write write Input 1
add_interface_port joy joy_writedata writedata Input 8
set_interface_assignment joy embeddedsw.configuration.isFlash 0
set_interface_assignment joy embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment joy embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment joy embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point conduit_joystick
# 
add_interface conduit_joystick conduit end
set_interface_property conduit_joystick associatedClock ""
set_interface_property conduit_joystick associatedReset ""
set_interface_property conduit_joystick ENABLED true
set_interface_property conduit_joystick EXPORT_OF ""
set_interface_property conduit_joystick PORT_NAME_MAP ""
set_interface_property conduit_joystick CMSIS_SVD_VARIABLES ""
set_interface_property conduit_joystick SVD_ADDRESS_GROUP ""

add_interface_port conduit_joystick joystick_0 joystick_0 Input 12
add_interface_port conduit_joystick joystick_1 joystick_1 Input 12

