# TCL File Generated by Component Editor 17.0
# Thu Apr 05 06:19:48 CST 2018
# DO NOT MODIFY


# 
# width_trans "width_trans" v17.0
# Sorgelig 2018.04.05.06:19:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module width_trans
# 
set_module_property DESCRIPTION ""
set_module_property NAME width_trans
set_module_property VERSION 17.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Sorgelig
set_module_property DISPLAY_NAME width_trans
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL width_trans
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file width_trans.v VERILOG PATH width_trans.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point in
# 
add_interface in avalon end
set_interface_property in addressUnits SYMBOLS
set_interface_property in associatedClock clock
set_interface_property in associatedReset reset
set_interface_property in bitsPerSymbol 8
set_interface_property in burstOnBurstBoundariesOnly false
set_interface_property in burstcountUnits WORDS
set_interface_property in explicitAddressSpan 0
set_interface_property in holdTime 0
set_interface_property in linewrapBursts false
set_interface_property in maximumPendingReadTransactions 0
set_interface_property in maximumPendingWriteTransactions 0
set_interface_property in readLatency 1
set_interface_property in readWaitStates 0
set_interface_property in readWaitTime 0
set_interface_property in setupTime 0
set_interface_property in timingUnits Cycles
set_interface_property in writeWaitTime 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in in_address address Input 3
add_interface_port in in_read read Input 1
add_interface_port in in_readdata readdata Output 8
add_interface_port in in_write write Input 1
add_interface_port in in_writedata writedata Input 8
set_interface_assignment in embeddedsw.configuration.isFlash 0
set_interface_assignment in embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment in embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment in embeddedsw.configuration.isPrintableDevice 0


# 
# connection point out
# 
add_interface out avalon start
set_interface_property out addressUnits SYMBOLS
set_interface_property out associatedClock clock
set_interface_property out associatedReset reset
set_interface_property out bitsPerSymbol 8
set_interface_property out burstOnBurstBoundariesOnly false
set_interface_property out burstcountUnits WORDS
set_interface_property out doStreamReads false
set_interface_property out doStreamWrites false
set_interface_property out holdTime 0
set_interface_property out linewrapBursts false
set_interface_property out maximumPendingReadTransactions 0
set_interface_property out maximumPendingWriteTransactions 0
set_interface_property out readLatency 1
set_interface_property out readWaitTime 0
set_interface_property out setupTime 0
set_interface_property out timingUnits Cycles
set_interface_property out writeWaitTime 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_address address Output 9
add_interface_port out out_read read Output 1
add_interface_port out out_readdata readdata Input 32
add_interface_port out out_write write Output 1
add_interface_port out out_writedata writedata Output 32

