	system u0 (
		.clk_clk             (<connected-to-clk_clk>),             //        clk.clk
		.clk_sys_clk         (<connected-to-clk_sys_clk>),         //    clk_sys.clk
		.cpu_reset_reset     (<connected-to-cpu_reset_reset>),     //  cpu_reset.reset
		.ddram_address       (<connected-to-ddram_address>),       //      ddram.address
		.ddram_read          (<connected-to-ddram_read>),          //           .read
		.ddram_waitrequest   (<connected-to-ddram_waitrequest>),   //           .waitrequest
		.ddram_readdata      (<connected-to-ddram_readdata>),      //           .readdata
		.ddram_write         (<connected-to-ddram_write>),         //           .write
		.ddram_writedata     (<connected-to-ddram_writedata>),     //           .writedata
		.ddram_readdatavalid (<connected-to-ddram_readdatavalid>), //           .readdatavalid
		.ddram_byteenable    (<connected-to-ddram_byteenable>),    //           .byteenable
		.ddram_burstcount    (<connected-to-ddram_burstcount>),    //           .burstcount
		.disk_op_read        (<connected-to-disk_op_read>),        //       disk.op_read
		.disk_op_write       (<connected-to-disk_op_write>),       //           .op_write
		.disk_result_ok      (<connected-to-disk_result_ok>),      //           .result_ok
		.disk_result_error   (<connected-to-disk_result_error>),   //           .result_error
		.disk_op_device      (<connected-to-disk_op_device>),      //           .op_device
		.mem_waitrequest     (<connected-to-mem_waitrequest>),     //        mem.waitrequest
		.mem_readdata        (<connected-to-mem_readdata>),        //           .readdata
		.mem_readdatavalid   (<connected-to-mem_readdatavalid>),   //           .readdatavalid
		.mem_burstcount      (<connected-to-mem_burstcount>),      //           .burstcount
		.mem_writedata       (<connected-to-mem_writedata>),       //           .writedata
		.mem_address         (<connected-to-mem_address>),         //           .address
		.mem_write           (<connected-to-mem_write>),           //           .write
		.mem_read            (<connected-to-mem_read>),            //           .read
		.mem_byteenable      (<connected-to-mem_byteenable>),      //           .byteenable
		.mem_debugaccess     (<connected-to-mem_debugaccess>),     //           .debugaccess
		.pll_reset_reset     (<connected-to-pll_reset_reset>),     //  pll_reset.reset
		.ps2_kbclk_in        (<connected-to-ps2_kbclk_in>),        //        ps2.kbclk_in
		.ps2_kbdat_in        (<connected-to-ps2_kbdat_in>),        //           .kbdat_in
		.ps2_kbclk_out       (<connected-to-ps2_kbclk_out>),       //           .kbclk_out
		.ps2_kbdat_out       (<connected-to-ps2_kbdat_out>),       //           .kbdat_out
		.ps2_mouseclk_in     (<connected-to-ps2_mouseclk_in>),     //           .mouseclk_in
		.ps2_mousedat_in     (<connected-to-ps2_mousedat_in>),     //           .mousedat_in
		.ps2_mouseclk_out    (<connected-to-ps2_mouseclk_out>),    //           .mouseclk_out
		.ps2_mousedat_out    (<connected-to-ps2_mousedat_out>),    //           .mousedat_out
		.ps2_misc_a20_enable (<connected-to-ps2_misc_a20_enable>), //   ps2_misc.a20_enable
		.ps2_misc_reset_n    (<connected-to-ps2_misc_reset_n>),    //           .reset_n
		.qsys_reset_reset    (<connected-to-qsys_reset_reset>),    // qsys_reset.reset
		.sound_sample_l      (<connected-to-sound_sample_l>),      //      sound.sample_l
		.sound_sample_r      (<connected-to-sound_sample_r>),      //           .sample_r
		.sound_fm_mode       (<connected-to-sound_fm_mode>),       //           .fm_mode
		.sound_mpu_midi_in   (<connected-to-sound_mpu_midi_in>),   //           .mpu_midi_in
		.sound_mpu_midi_out  (<connected-to-sound_mpu_midi_out>),  //           .mpu_midi_out
		.speaker_enable      (<connected-to-speaker_enable>),      //    speaker.enable
		.speaker_out         (<connected-to-speaker_out>),         //           .out
		.uart_h_cts_n        (<connected-to-uart_h_cts_n>),        //     uart_h.cts_n
		.uart_h_rts_n        (<connected-to-uart_h_rts_n>),        //           .rts_n
		.uart_h_dsr_n        (<connected-to-uart_h_dsr_n>),        //           .dsr_n
		.uart_h_dcd_n        (<connected-to-uart_h_dcd_n>),        //           .dcd_n
		.uart_h_ri_n         (<connected-to-uart_h_ri_n>),         //           .ri_n
		.uart_h_dtr_n        (<connected-to-uart_h_dtr_n>),        //           .dtr_n
		.uart_h_out1_n       (<connected-to-uart_h_out1_n>),       //           .out1_n
		.uart_h_out2_n       (<connected-to-uart_h_out2_n>),       //           .out2_n
		.uart_s_sin          (<connected-to-uart_s_sin>),          //     uart_s.sin
		.uart_s_sout         (<connected-to-uart_s_sout>),         //           .sout
		.uart_s_sout_oe      (<connected-to-uart_s_sout_oe>),      //           .sout_oe
		.vga_clock           (<connected-to-vga_clock>),           //        vga.clock
		.vga_blank_n         (<connected-to-vga_blank_n>),         //           .blank_n
		.vga_hsync           (<connected-to-vga_hsync>),           //           .hsync
		.vga_vsync           (<connected-to-vga_vsync>),           //           .vsync
		.vga_r               (<connected-to-vga_r>),               //           .r
		.vga_g               (<connected-to-vga_g>),               //           .g
		.vga_b               (<connected-to-vga_b>)                //           .b
	);

