# TCL File Generated by Component Editor 17.0
# Mon Aug 03 14:54:54 CST 2020
# DO NOT MODIFY


# 
# hdd "hdd" v1.0
#  2020.08.03.14:54:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hdd
# 
set_module_property DESCRIPTION ""
set_module_property NAME hdd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ao486
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hdd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hdd
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hdd.v VERILOG PATH hdd.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point io
# 
add_interface io avalon end
set_interface_property io addressUnits WORDS
set_interface_property io associatedClock clock
set_interface_property io associatedReset reset_sink
set_interface_property io bitsPerSymbol 8
set_interface_property io burstOnBurstBoundariesOnly false
set_interface_property io burstcountUnits WORDS
set_interface_property io explicitAddressSpan 0
set_interface_property io holdTime 0
set_interface_property io linewrapBursts false
set_interface_property io maximumPendingReadTransactions 0
set_interface_property io maximumPendingWriteTransactions 0
set_interface_property io readLatency 0
set_interface_property io readWaitTime 1
set_interface_property io setupTime 0
set_interface_property io timingUnits Cycles
set_interface_property io writeWaitTime 0
set_interface_property io ENABLED true
set_interface_property io EXPORT_OF ""
set_interface_property io PORT_NAME_MAP ""
set_interface_property io CMSIS_SVD_VARIABLES ""
set_interface_property io SVD_ADDRESS_GROUP ""

add_interface_port io io_address address Input 1
add_interface_port io io_byteenable byteenable Input 4
add_interface_port io io_read read Input 1
add_interface_port io io_readdata readdata Output 32
add_interface_port io io_write write Input 1
add_interface_port io io_writedata writedata Input 32
set_interface_assignment io embeddedsw.configuration.isFlash 0
set_interface_assignment io embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment io embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment io embeddedsw.configuration.isPrintableDevice 0


# 
# connection point mgmt
# 
add_interface mgmt avalon end
set_interface_property mgmt addressUnits WORDS
set_interface_property mgmt associatedClock clock
set_interface_property mgmt associatedReset reset_sink
set_interface_property mgmt bitsPerSymbol 8
set_interface_property mgmt burstOnBurstBoundariesOnly false
set_interface_property mgmt burstcountUnits WORDS
set_interface_property mgmt explicitAddressSpan 0
set_interface_property mgmt holdTime 0
set_interface_property mgmt linewrapBursts false
set_interface_property mgmt maximumPendingReadTransactions 0
set_interface_property mgmt maximumPendingWriteTransactions 0
set_interface_property mgmt readLatency 0
set_interface_property mgmt readWaitTime 1
set_interface_property mgmt setupTime 0
set_interface_property mgmt timingUnits Cycles
set_interface_property mgmt writeWaitTime 0
set_interface_property mgmt ENABLED true
set_interface_property mgmt EXPORT_OF ""
set_interface_property mgmt PORT_NAME_MAP ""
set_interface_property mgmt CMSIS_SVD_VARIABLES ""
set_interface_property mgmt SVD_ADDRESS_GROUP ""

add_interface_port mgmt mgmt_address address Input 3
add_interface_port mgmt mgmt_write write Input 1
add_interface_port mgmt mgmt_writedata writedata Input 32
add_interface_port mgmt mgmt_read read Input 1
add_interface_port mgmt mgmt_readdata readdata Output 32
set_interface_assignment mgmt embeddedsw.configuration.isFlash 0
set_interface_assignment mgmt embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mgmt embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mgmt embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint io
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point conduit_ide_3f6
# 
add_interface conduit_ide_3f6 conduit end
set_interface_property conduit_ide_3f6 associatedClock clock
set_interface_property conduit_ide_3f6 associatedReset reset_sink
set_interface_property conduit_ide_3f6 ENABLED true
set_interface_property conduit_ide_3f6 EXPORT_OF ""
set_interface_property conduit_ide_3f6 PORT_NAME_MAP ""
set_interface_property conduit_ide_3f6 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_ide_3f6 SVD_ADDRESS_GROUP ""

add_interface_port conduit_ide_3f6 ide_3f6_read ide_3f6_read Input 1
add_interface_port conduit_ide_3f6 ide_3f6_readdata ide_3f6_readdata Output 8
add_interface_port conduit_ide_3f6 ide_3f6_write ide_3f6_write Input 1
add_interface_port conduit_ide_3f6 ide_3f6_writedata ide_3f6_writedata Input 8


# 
# connection point req
# 
add_interface req conduit end
set_interface_property req associatedClock clock
set_interface_property req associatedReset ""
set_interface_property req ENABLED true
set_interface_property req EXPORT_OF ""
set_interface_property req PORT_NAME_MAP ""
set_interface_property req CMSIS_SVD_VARIABLES ""
set_interface_property req SVD_ADDRESS_GROUP ""

add_interface_port req dat_request dat_request Output 3
add_interface_port req dat_read dat_read Input 1
add_interface_port req dat_write dat_write Input 1
add_interface_port req dat_writedata dat_writedata Input 16
add_interface_port req dat_readdata dat_readdata Output 16

