// Ported for the ao486 NE2000 (Phase 1 of NE2000_AO486_PLAN.md) from the
// Minimig-AGA Ethernet_shmem2 branch, commit 9598b936
// (apolkosnik/Minimig-AGA_MiSTer, GPL). Module renamed; logic unchanged.
//
//
// ne2000_ddr_mailbox.v
//
// NE2000/RTL8019 ethernet DDR3 mailbox master.
//
// Bridges the existing 16-bit eth_dma_* master interface (generated by
// rtl/ethernet.v in the clk_sys domain) onto a 64-bit Avalon-MM master in the
// clk_audio domain, which is arbitrated onto the f2sdram2 (ram2) port via
// eth_avalon_arbiter.  This is the A2065-style dedicated-mailbox transport,
// replacing the previous piggyback onto the Amiga DDR controller.
//
// Single source of truth for the shared window:
//   HPS physical base  : 0x1FF00000   (reserved high DDR; matches A2065)
//   f2sdram2 word base : 0x1FF00000 >> 3 = 0x03FE0000   (port is 64-bit)
// The HPS (extra/minimig_eth.cpp) mmaps /dev/mem at 0x1FF00000 so the FPGA and
// the ARM access exactly the same bytes.
//
// Byte-lane / endian convention (identical to the old ddram_ctrl path, verified
// by sim/eth_dma_lane_tb.v so ethernet.v and the HPS daemon are unchanged):
//   - eth_dma_addr[15:1] is a 16-bit-word offset inside the 64KB window.
//   - 64-bit word index = base + eth_dma_addr[15:3]; lane = eth_dma_addr[2:1].
//   - eth_dma_uds / eth_dma_lds are ACTIVE-LOW byte selects (68k _UDS/_LDS).
//   - Within the 64-bit word, lane L uses bytes [2L] and [2L+1]:
//       byte[2L]   = Amiga upper byte (eth_dma_wdata[15:8]), enable = ~uds
//       byte[2L+1] = Amiga lower byte (eth_dma_wdata[7:0]),  enable = ~lds
//     i.e. the 16-bit field stored at the lane is {wdata[7:0], wdata[15:8]}.
//   - On read, the returned eth_dma_rdata swaps the raw lane field back to Amiga
//     orientation: {raw[7:0], raw[15:8]}.
//
// CDC: a single outstanding request crosses clk_sys -> clk_audio via a toggle
// (req) and clk_audio -> clk_sys via a toggle (done).  The request payload
// (addr/wdata/write/uds/lds) is latched in clk_sys before the request toggle
// flips and is held stable by ethernet.v until eth_dma_ready, so it can be
// sampled in clk_audio without a per-bit synchronizer (standard MCP handshake).
//

module ne2000_ddr_mailbox
(
    // ---- clk_sys side: connects to ethernet.v eth_dma_* master ----
    input             clk_sys,
    input             reset_sys,
    input             eth_dma_req,        // held high until eth_dma_ready
    input             eth_dma_write,
    input      [15:1] eth_dma_addr,       // 16-bit-word offset within 64KB window
    input      [15:0] eth_dma_wdata,
    input             eth_dma_uds,        // active-low upper-byte select
    input             eth_dma_lds,        // active-low lower-byte select
    // 64-bit "wide" packing: when eth_dma_wide is high at the rising edge of
    // eth_dma_req, the whole 64-bit DDR word (all four 16-bit lanes) is moved
    // in one Avalon transaction.  eth_dma_addr must be 64-bit aligned (byte
    // addr[2:0]==0).  Lane L holds the 16-bit word at byte (base+2L); each lane
    // is byte-swapped exactly like the per-lane 16-bit path so the on-wire DDR
    // bytes are identical to four single-lane transfers.
    input             eth_dma_wide,
    input      [63:0] eth_dma_wdata64,    // lane0=[15:0] .. lane3=[63:48]
    output reg        eth_dma_ready,      // 1-cycle pulse (clk_sys) on completion
    output reg [15:0] eth_dma_rdata,
    output reg [63:0] eth_dma_rdata64,    // valid with eth_dma_ready on a wide read

    // ---- clk_audio side: Avalon-MM master to eth_avalon_arbiter (m1) ----
    input             clk_avl,
    input             reset_avl,
    output reg [28:0] avl_address,
    output reg [ 7:0] avl_burstcount,
    output reg [ 7:0] avl_byteenable,
    output reg [63:0] avl_writedata,
    output reg        avl_read,
    output reg        avl_write,
    input             avl_waitrequest,
    input      [63:0] avl_readdata,
    input             avl_readdatavalid,

    // ---- debug (clk_avl): for an ISSP probe in the parent ----
    output     [63:0] dbg
);

    // ----------------------------------------------------------------
    // clk_sys: latch request payload and toggle on the rising edge of req
    // ----------------------------------------------------------------
    reg        done_toggle   = 1'b0;     // clk_avl -> clk_sys (declared early; written in clk_avl block)
    reg        req_d         = 1'b0;
    reg        req_toggle    = 1'b0;     // clk_sys -> clk_avl
    reg [15:1] addr_hold     = 15'h0000;
    reg [15:0] wdata_hold    = 16'h0000;
    reg [63:0] wdata64_hold  = 64'h0;
    reg        write_hold    = 1'b0;
    reg        wide_hold     = 1'b0;
    reg        uds_hold       = 1'b1;
    reg        lds_hold       = 1'b1;

    // clk_avl -> clk_sys done handshake
    reg        done_meta     = 1'b0;
    reg        done_sync     = 1'b0;
    reg        done_sync_d   = 1'b0;
    reg [15:0] rdata_avl      = 16'h0000;
    reg [63:0] rdata_avl64    = 64'h0;

    wire done_pulse_sys = done_sync ^ done_sync_d;

    always @(posedge clk_sys) begin
        if (reset_sys) begin
            req_d        <= 1'b0;
            req_toggle   <= 1'b0;
            addr_hold    <= 15'h0000;
            wdata_hold   <= 16'h0000;
            wdata64_hold <= 64'h0;
            write_hold   <= 1'b0;
            wide_hold    <= 1'b0;
            uds_hold     <= 1'b1;
            lds_hold     <= 1'b1;
            done_meta    <= 1'b0;
            done_sync    <= 1'b0;
            done_sync_d  <= 1'b0;
            eth_dma_ready<= 1'b0;
            eth_dma_rdata<= 16'h0000;
            eth_dma_rdata64 <= 64'h0;
        end else begin
            req_d <= eth_dma_req;
            if (eth_dma_req && !req_d) begin
                addr_hold    <= eth_dma_addr;
                wdata_hold   <= eth_dma_wdata;
                wdata64_hold <= eth_dma_wdata64;
                write_hold   <= eth_dma_write;
                wide_hold    <= eth_dma_wide;
                uds_hold     <= eth_dma_uds;
                lds_hold     <= eth_dma_lds;
                req_toggle   <= ~req_toggle;
            end

            done_meta   <= done_toggle;
            done_sync   <= done_meta;
            done_sync_d <= done_sync;

            eth_dma_ready <= done_pulse_sys;
            if (done_pulse_sys) begin
                eth_dma_rdata   <= rdata_avl;
                eth_dma_rdata64 <= rdata_avl64;
            end
        end
    end

    // ----------------------------------------------------------------
    // clk_avl: synchronize request toggle, run the Avalon transaction
    // ----------------------------------------------------------------
    reg        req_meta      = 1'b0;
    reg        req_sync      = 1'b0;
    reg        req_sync_d    = 1'b0;

    wire req_pulse_avl = req_sync ^ req_sync_d;

    localparam S_IDLE = 2'd0;
    localparam S_CMD  = 2'd1;
    localparam S_READ = 2'd2;

    reg [1:0] state = S_IDLE;
    reg [1:0] cap_lane  = 2'd0;
    reg       cap_write = 1'b0;

    // Byte-swap each of the four 16-bit lanes of a 64-bit word, matching the
    // per-lane swap of the 16-bit path ({wdata[7:0],wdata[15:8]}).  Applying
    // this to a packed 64-bit write (or to avl_readdata on a read) yields DDR
    // bytes identical to four single-lane transfers.
    function [63:0] wide_swap16;
        input [63:0] x;
        begin
            wide_swap16 = { x[55:48], x[63:56],
                            x[39:32], x[47:40],
                            x[23:16], x[31:24],
                            x[ 7:0 ], x[15:8 ] };
        end
    endfunction

    // Debug counters (clk_avl) for the ISSP probe in the parent.
    reg [7:0] dbg_wr_accept = 8'd0;   // writes accepted (avl_write & !waitrequest)
    reg [7:0] dbg_rd_accept = 8'd0;   // reads  accepted (avl_read  & !waitrequest)
    reg [7:0] dbg_rdvalid   = 8'd0;   // readdatavalid beats
    reg [7:0] dbg_wr_stall  = 8'd0;   // cycles a write was offered but waitrequested
    assign dbg = {
        24'd0,
        avl_readdatavalid, avl_waitrequest, avl_read, avl_write,  // [39:36]
        state, 2'd0,                                              // [35:32]
        dbg_wr_stall,                                             // [31:24]
        dbg_rdvalid,                                              // [23:16]
        dbg_rd_accept,                                            // [15:8]
        dbg_wr_accept                                             // [7:0]
    };

    // Combinational decode of the (stable) held request payload.
    // ne2000_dma_addr_map is the single source of truth for the f2sdram2 base.
    wire [28:0] req_word_addr;
    ne2000_dma_addr_map addr_map_i
    (
        .local_word_addr(addr_hold),
        .ddr_word_addr  (req_word_addr)
    );
    wire [1:0]  req_lane      = addr_hold[2:1];
    wire [15:0] req_swapped   = {wdata_hold[7:0], wdata_hold[15:8]};
    wire [5:0]  req_lane_bit  = {req_lane, 4'd0};           // lane * 16
    // Replicate the 16-bit data across all four 64-bit lanes, exactly like the
    // proven ddram_ctrl write path (DDRAM_DIN <= {d,d,d,d}); avl_byteenable
    // selects the active lane. Some f2sdram write paths want full-word data.
    wire [63:0] req_wdata64   = {req_swapped, req_swapped, req_swapped, req_swapped};
    wire [7:0]  req_be8       = {6'd0, ~lds_hold, ~uds_hold} << {req_lane, 1'b0};

    // Read-data lane extraction.
    wire [5:0]  cap_lane_bit  = {cap_lane, 4'd0};
    wire [15:0] rd_raw_field  = avl_readdata[cap_lane_bit +: 16];

    always @(posedge clk_avl) begin
        if (reset_avl) begin
            req_meta    <= 1'b0;
            req_sync    <= 1'b0;
            req_sync_d  <= 1'b0;
            done_toggle <= 1'b0;
            state       <= S_IDLE;
            avl_read    <= 1'b0;
            avl_write   <= 1'b0;
            avl_address <= 29'd0;
            avl_burstcount <= 8'd1;
            avl_byteenable <= 8'h00;
            avl_writedata  <= 64'd0;
            rdata_avl   <= 16'h0000;
            rdata_avl64 <= 64'h0;
            cap_lane    <= 2'd0;
            cap_write   <= 1'b0;
            dbg_wr_accept <= 8'd0;
            dbg_rd_accept <= 8'd0;
            dbg_rdvalid   <= 8'd0;
            dbg_wr_stall  <= 8'd0;
        end else begin
            req_meta   <= req_toggle;
            req_sync   <= req_meta;
            req_sync_d <= req_sync;

            // Debug accounting: did the f2sdram2 slave accept our commands?
            if (avl_write &&  avl_waitrequest) dbg_wr_stall  <= dbg_wr_stall  + 8'd1;
            if (avl_write && !avl_waitrequest) dbg_wr_accept <= dbg_wr_accept + 8'd1;
            if (avl_read  && !avl_waitrequest) dbg_rd_accept <= dbg_rd_accept + 8'd1;
            if (avl_readdatavalid)             dbg_rdvalid   <= dbg_rdvalid   + 8'd1;

            case (state)
                S_IDLE: begin
                    avl_read  <= 1'b0;
                    avl_write <= 1'b0;
                    if (req_pulse_avl) begin
                        cap_lane       <= req_lane;
                        cap_write      <= write_hold;
                        avl_address    <= req_word_addr;
                        avl_burstcount <= 8'd1;
                        if (write_hold) begin
                            avl_writedata  <= wide_hold ? wide_swap16(wdata64_hold)
                                                        : req_wdata64;
                            avl_byteenable <= wide_hold ? 8'hFF : req_be8;
                            avl_write      <= 1'b1;
                            avl_read       <= 1'b0;
                        end else begin
                            avl_byteenable <= 8'hFF;
                            avl_read       <= 1'b1;
                            avl_write      <= 1'b0;
                        end
                        state <= S_CMD;
                    end
                end

                S_CMD: begin
                    // Hold command stable until the slave accepts it.
                    if (!avl_waitrequest) begin
                        if (cap_write) begin
                            avl_write   <= 1'b0;
                            rdata_avl   <= 16'h0000;
                            done_toggle <= ~done_toggle;   // posted write complete
                            state       <= S_IDLE;
                        end else begin
                            avl_read <= 1'b0;              // read command accepted
                            state    <= S_READ;
                        end
                    end
                end

                S_READ: begin
                    if (avl_readdatavalid) begin
                        rdata_avl   <= {rd_raw_field[7:0], rd_raw_field[15:8]};
                        rdata_avl64 <= wide_swap16(avl_readdata);
                        done_toggle <= ~done_toggle;
                        state       <= S_IDLE;
                    end
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule
