# TCL File Generated by Component Editor 17.0
# Tue Aug 04 18:07:08 CST 2020
# DO NOT MODIFY


# 
# sound "sound" v1.0
#  2020.08.04.18:07:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sound
# 
set_module_property DESCRIPTION ""
set_module_property NAME sound
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ao486
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sound
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sound
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sound.v VERILOG PATH sound.v TOP_LEVEL_FILE
add_fileset_file sound_dsp.v VERILOG PATH sound_dsp.v
add_fileset_file simple_single_rom.v VERILOG PATH ../../common/simple_single_rom.v
add_fileset_file NextZ80ALU.v VERILOG PATH opl3/NextZ80ALU.v
add_fileset_file NextZ80CPU.v VERILOG PATH opl3/NextZ80CPU.v
add_fileset_file NextZ80Reg.v VERILOG PATH opl3/NextZ80Reg.v
add_fileset_file compressor.sv SYSTEM_VERILOG PATH opl3/compressor.sv
add_fileset_file opl3.sv SYSTEM_VERILOG PATH opl3/opl3.sv
add_fileset_file opl3fm.sv SYSTEM_VERILOG PATH opl3/opl3fm.sv
add_fileset_file opl3seq.sv SYSTEM_VERILOG PATH opl3/opl3seq.sv
add_fileset_file opl3prg.mem OTHER PATH opl3/opl3prg.mem
add_fileset_file exp_tab.mem OTHER PATH opl3/exp_tab.mem
add_fileset_file sin_tab_full.mem OTHER PATH opl3/sin_tab_full.mem


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point io
# 
add_interface io avalon end
set_interface_property io addressUnits WORDS
set_interface_property io associatedClock clock
set_interface_property io associatedReset reset_sink
set_interface_property io bitsPerSymbol 8
set_interface_property io burstOnBurstBoundariesOnly false
set_interface_property io burstcountUnits WORDS
set_interface_property io explicitAddressSpan 0
set_interface_property io holdTime 0
set_interface_property io linewrapBursts false
set_interface_property io maximumPendingReadTransactions 0
set_interface_property io maximumPendingWriteTransactions 0
set_interface_property io readLatency 0
set_interface_property io readWaitStates 0
set_interface_property io readWaitTime 0
set_interface_property io setupTime 0
set_interface_property io timingUnits Cycles
set_interface_property io writeWaitTime 0
set_interface_property io ENABLED true
set_interface_property io EXPORT_OF ""
set_interface_property io PORT_NAME_MAP ""
set_interface_property io CMSIS_SVD_VARIABLES ""
set_interface_property io SVD_ADDRESS_GROUP ""

add_interface_port io io_address address Input 4
add_interface_port io io_read read Input 1
add_interface_port io io_readdata readdata Output 8
add_interface_port io io_write write Input 1
add_interface_port io io_writedata writedata Input 8
set_interface_assignment io embeddedsw.configuration.isFlash 0
set_interface_assignment io embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment io embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment io embeddedsw.configuration.isPrintableDevice 0


# 
# connection point fm
# 
add_interface fm avalon end
set_interface_property fm addressUnits WORDS
set_interface_property fm associatedClock clock
set_interface_property fm associatedReset reset_sink
set_interface_property fm bitsPerSymbol 8
set_interface_property fm burstOnBurstBoundariesOnly false
set_interface_property fm burstcountUnits WORDS
set_interface_property fm explicitAddressSpan 0
set_interface_property fm holdTime 0
set_interface_property fm linewrapBursts false
set_interface_property fm maximumPendingReadTransactions 0
set_interface_property fm maximumPendingWriteTransactions 0
set_interface_property fm readLatency 0
set_interface_property fm readWaitStates 0
set_interface_property fm readWaitTime 0
set_interface_property fm setupTime 0
set_interface_property fm timingUnits Cycles
set_interface_property fm writeWaitTime 0
set_interface_property fm ENABLED true
set_interface_property fm EXPORT_OF ""
set_interface_property fm PORT_NAME_MAP ""
set_interface_property fm CMSIS_SVD_VARIABLES ""
set_interface_property fm SVD_ADDRESS_GROUP ""

add_interface_port fm fm_address address Input 2
add_interface_port fm fm_read read Input 1
add_interface_port fm fm_readdata readdata Output 8
add_interface_port fm fm_write write Input 1
add_interface_port fm fm_writedata writedata Input 8
set_interface_assignment fm embeddedsw.configuration.isFlash 0
set_interface_assignment fm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment fm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment fm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point conduit_dma_soundblaster
# 
add_interface conduit_dma_soundblaster conduit end
set_interface_property conduit_dma_soundblaster associatedClock clock
set_interface_property conduit_dma_soundblaster associatedReset reset_sink
set_interface_property conduit_dma_soundblaster ENABLED true
set_interface_property conduit_dma_soundblaster EXPORT_OF ""
set_interface_property conduit_dma_soundblaster PORT_NAME_MAP ""
set_interface_property conduit_dma_soundblaster CMSIS_SVD_VARIABLES ""
set_interface_property conduit_dma_soundblaster SVD_ADDRESS_GROUP ""

add_interface_port conduit_dma_soundblaster dma_soundblaster_req dma_soundblaster_req Output 1
add_interface_port conduit_dma_soundblaster dma_soundblaster_ack dma_soundblaster_ack Input 1
add_interface_port conduit_dma_soundblaster dma_soundblaster_terminal dma_soundblaster_terminal Input 1
add_interface_port conduit_dma_soundblaster dma_soundblaster_readdata dma_soundblaster_readdata Input 8
add_interface_port conduit_dma_soundblaster dma_soundblaster_writedata dma_soundblaster_writedata Output 8


# 
# connection point conduit_sound
# 
add_interface conduit_sound conduit end
set_interface_property conduit_sound associatedClock clock
set_interface_property conduit_sound associatedReset ""
set_interface_property conduit_sound ENABLED true
set_interface_property conduit_sound EXPORT_OF ""
set_interface_property conduit_sound PORT_NAME_MAP ""
set_interface_property conduit_sound CMSIS_SVD_VARIABLES ""
set_interface_property conduit_sound SVD_ADDRESS_GROUP ""

add_interface_port conduit_sound sample_l sample_l Output 16
add_interface_port conduit_sound sample_r sample_r Output 16
add_interface_port conduit_sound fm_mode fm_mode Input 1
add_interface_port conduit_sound clock_rate clock_rate Input 28


# 
# connection point clock_opl
# 
add_interface clock_opl clock end
set_interface_property clock_opl clockRate 0
set_interface_property clock_opl ENABLED true
set_interface_property clock_opl EXPORT_OF ""
set_interface_property clock_opl PORT_NAME_MAP ""
set_interface_property clock_opl CMSIS_SVD_VARIABLES ""
set_interface_property clock_opl SVD_ADDRESS_GROUP ""

add_interface_port clock_opl clk_opl clk Input 1

